services:

  # Django приложение
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - logs_volume:/app/logs
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=${DB_NAME:-postgres}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-5432}
      - SECRET_KEY=${SECRET_KEY:-}
      - DEBUG=${DEBUG:-True}
      - MATTERMOST_WEBHOOK_URL=${MATTERMOST_WEBHOOK_URL:-}
      - MATTERMOST_CHANNEL=${MATTERMOST_CHANNEL:-}
    restart: unless-stopped

  # Cron для автоматической проверки обновлений
  cron:
    build: .
    user: root
    command: /app/start-cron.sh
    volumes:
      - .:/app
      - logs_volume:/app/logs
    environment:
      - DB_NAME=${DB_NAME:-postgres}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG:-False}
      - MATTERMOST_WEBHOOK_URL=${MATTERMOST_WEBHOOK_URL:-}
      - MATTERMOST_CHANNEL=${MATTERMOST_CHANNEL:-}
    restart: unless-stopped

volumes:
  static_volume:
  logs_volume:
