# Generated by Django 5.2.6 on 2025-09-14 15:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_code', models.CharField(max_length=255, unique=True, verbose_name='Код шаблона')),
                ('current_version', models.CharField(max_length=50, verbose_name='Текущая версия')),
                ('last_checked', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последняя проверка')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('inactive', 'Не активен')], default='active', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
                'ordering': ['template_code'],
            },
        ),
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_version', models.CharField(max_length=50, verbose_name='Старая версия')),
                ('new_version', models.CharField(max_length=50, verbose_name='Новая версия')),
                ('priority', models.CharField(choices=[('critical', 'Критический'), ('normal', 'Средний')], default='normal', max_length=10, verbose_name='Приоритет')),
                ('has_validation_changes', models.BooleanField(default=False, verbose_name='Изменения в проверках')),
                ('message_status', models.CharField(choices=[('SENT', 'Отправлено'), ('NOTSENT', 'Не отправлено')], default='NOTSENT', max_length=10, verbose_name='Статус сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('raw_xml', models.TextField(blank=True, null=True, verbose_name='Исходный XML')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templates.template', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Лог обновления',
                'verbose_name_plural': 'Логи обновлений',
                'ordering': ['-created_at'],
            },
        ),
    ]
