# Generated by Django 5.2.6 on 2025-09-14 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatelog',
            name='priority',
        ),
    ]
